//ICC-AVR 
// Target : M64
// Crystal: 11.0592M

//Command List
//==============================================================================

//===========================public command list================================
const uchar   Fixture_Information[]=			{"fixture information"};
const uchar   Help[]=							{"help"};
const uchar   Reset_Fixture[]=					{"reset fixture"};
const uchar   Code_VER[]=						{"code ver."}; 
const uchar   Open_North_Magnetic_Field[]=		{"open north magnetic field"};
const uchar   Close_North_Magnetic_Field[]=		{"close north magnetic field"};
const uchar   Open_South_Magnetic_Field[]=		{"open south magnetic field"};
const uchar   Close_South_Magnetic_Field[]=		{"close south magnetic field"};
const uchar   Magnetic_Field_Up[]=				{"magnetic field up"};
const uchar   Magnetic_Field_Down[]=			{"magnetic field down"};

const uchar   Set_Coil_Current[]=				{"set coil current"}; 
const uchar   Set_Current_Offset[]=				{"set current offset"}; 
const uchar   Set_Fixture_Ratio[]=				{"set fixture ratio"};
const uchar   Calculate_Fixture_Ratio[]=		{"calculate fixture ratio"}; 
const uchar   Read_Data[]=						{"read data"}; 
const uchar   Read_Coil_Current[]=				{"read coil current"};
const uchar   Read[]=							{"read"}; 
const uchar   Sample_1[]=						{"sample 1"}; 
const uchar   Sample[]=							{"sample"}; 
const uchar   Sample_magnetic[]=				{"sample magnetic"}; 
const uchar   Read_Compass_data[]=				{"Read Compass data"}; 
const uchar   Set_A[]=							{"set a"}; 
const uchar   Set_B[]=							{"set b"}; 
const uchar   Set_DA[]=							{"set da"}; 
const uchar   Set_Info[]=						{"set info"}; 
const uchar   Set_Date[]=						{"set date"}; 
const uchar   Set_SN[]=							{"set sn"}; 

const uchar   up[]=								{"up"}; 
const uchar   down[]=							{"down"}; 
const uchar   Test1[]=							{"test1"}; 
const uchar   Test2[]=							{"test2"}; 






uchar	SY[]=					{"@_@"};
uchar	error[]=				{"This command is illegal,please check it again"};
 
//==============================================================================

	